<div class="row">
	<div class="col-lg-12 quote-container">
		<div class="quote">
			<!-- Quote generated by the script at the end -->
			<p id="text-quote"></p>
			<span id="quote-left"
				class="glyphicon glyphicon-chevron-left smaller"
				style="display: none"></span> <span id="quote-right"
				class="glyphicon glyphicon-chevron-right smaller"></span>
		</div>
	</div>
</div>